path: /home/fosterz/repositories/quiltr/inst/doc
output: /tmp/RtmpipSnUF/file3f474c8c3110
name: Quiltr
clean: yes
overwrite: yes
theme: cosmo
apply_theme: yes
cumulative: no
use_file_names: yes
use_dir_names: no
use_config_files: yes
name_sep: '-'
use_file_suffix: yes
use_dir_suffix: yes
note_config_name: placement.yml
site_config_name: website_build_config.yml
site_config_file: /home/fosterz/repositories/quiltr
output_dir_name: website
partial_copy: no
open: yes
