path: /home/local/USDA-ARS/fosterz/repositories/quiltr/inst/doc
output: /tmp/Rtmp5sGXQf/file4b0d26373d39
name: Quiltr
clean: yes
overwrite: yes
theme: flatly
apply_theme: yes
cumulative: no
use_file_names: yes
use_dir_names: no
use_config_files: yes
name_sep: '-'
use_file_suffix: yes
use_dir_suffix: yes
note_config_name: placement.yml
site_config_name: website_build_config.yml
site_config_file: /home/local/USDA-ARS/fosterz/repositories/quiltr
output_dir_name: website
partial_copy: no
open: yes
