path: /home/local/USDA-ARS/fosterz/repositories/quiltr/vignettes
output: /tmp/RtmpuWRYF3/file38b55e0f53a5
type:
- html
- rmd
name: Quiltr
clean: yes
overwrite: no
theme: flatly
apply_theme: yes
cumulative: no
use_file_names: yes
use_dir_names: no
use_config_files: yes
name_sep: '-'
use_file_suffix: yes
use_dir_suffix: yes
menu_name_parser: !expr |
  function (x)
  gsub("^[0-9]*_", "", x)
note_config_name: placement.yml
site_config_name: website_build_config.yml
site_config_file: /home/local/USDA-ARS/fosterz/repositories/quiltr
output_dir_name: website
partial_copy: no
open: yes
