path: /home/fosterz/repositories/quiltr/vignette_examples/test_website_2
output: /home/fosterz/repositories/quiltr/inst/doc
clean: yes
overwrite: yes
theme: cerulean
apply_theme: yes
cumulative: yes
use_file_names: yes
use_dir_names: yes
use_config_files: yes
name_sep: '-'
use_file_suffix: no
use_dir_suffix: yes
note_config_name: note_config.yml
site_config_name: website_build_config.yml
site_config_file: /home/fosterz/repositories/quiltr/vignette_examples/test_website_2
output_dir_name: test_website_2
open: no
