name: Example
theme: flatly
apply_theme: yes
use_file_names: yes
use_file_suffix: yes
name_sep: "-"
menu_name_parser: !expr function(x) gsub('^[0-9]*_', '', x)
placement:
- 'home.Rmd': ""
- '*_is_ignored.Rmd':
